site_name: JavaScript Catalog
site_url: https://jsdocs.sprai.org
site_description: Documentation of the JavaScript Catalog System
theme: cinder
site_author: Paul Murley

markdown_extensions:
    - codehilite

pages:
    - 'Overview' : 'index.md'
    - 'Using Data' : 'using-data.md'
    - 'Crawling Quickstart' : 'quickstart-crawling.md'
    - 'Crawl Tasks' : 'crawl-tasks.md'
